const literaryFunFacts = [
  "Dr. Seuss wrote over 60 books, including *The Cat in the Hat* and *Green Eggs and Ham*.",
  "The longest novel ever written is *In Search of Lost Time* by Marcel Proust. It has over 4,000 pages!",
  "J.K. Rowling wrote the first *Harry Potter* book in cafes while living as a single mom with little money.",
  "Walt Disney was inspired by *Peter Pan* for the creation of Disneyland.",
  "The first-ever children's book was *The Tale of Peter Rabbit* by Beatrix Potter.",
  "*The Wizard of Oz* was originally a book, written by L. Frank Baum in 1900, long before it became a famous movie.",
  "Shakespeare invented over 1,700 words! Some of them are 'lonely,' 'eyeball,' and 'swagger.'",
  "*Alice in Wonderland* has been translated into more than 170 languages!",
  "The *Harry Potter* books are among the most translated books in the world!",
  "Roald Dahl, the famous author of *Charlie and the Chocolate Factory*, was a pilot in World War II.",
  "The longest word in English literature is a 189,819-letter word in the book *Marienbad My Love* by Mark Leach.",
  "Mary Shelley wrote *Frankenstein* when she was just 18 years old!",
  "The first library card was issued in 1892 in the United States.",
  "The first book printed using movable type was the Gutenberg Bible in the 1450s.",
  "Enid Blyton wrote over 700 books, including the famous *Famous Five* and *Secret Seven* series.",
  "*The Chronicles of Narnia* is a series of seven books written by C.S. Lewis, and it's inspired by Greek and Norse mythology!",
  "*The Little Mermaid* by Hans Christian Andersen was written as a sad story, not a happy one like the Disney version.",
  "*Matilda*, the little girl with telekinetic powers in Roald Dahl's book, was inspired by his own love for smart, strong-willed kids.",
  "Winnie the Pooh's full name is Edward Bear.",
  "The word 'bookkeeper' is the only word in the English language with three consecutive double letters!",
  "The first comic book was published in 1933 and was called *Action Comics No. 1*, introducing Superman.",
  "L. Frank Baum wrote 14 books about Dorothy and the land of Oz.",
  "The first book ever printed in the U.S. was the *Bay Psalm Book* in 1640.",
  "The longest book title in history is 1,266 words long!",
  "The fastest-selling book of all time is *Harry Potter and the Deathly Hallows*.",
  "The original *Winnie the Pooh* stories were inspired by A.A. Milne's son, Christopher Robin, and his stuffed animals.",
  "The most expensive book ever sold is Leonardo da Vinci's *Codex Leicester*, which was bought for $30.8 million.",
  "The longest-running book series is *The Hardy Boys*, which has over 190 titles.",
  "The famous *Diary of a Wimpy Kid* series by Jeff Kinney was originally published online before being turned into books.",
  "C.S. Lewis, author of *The Chronicles of Narnia*, was also a professor of medieval literature at Oxford University.",
  "The first edition of *The Hobbit* was published in 1937 with a print run of just 1,500 copies.",
  "The author of *The Adventures of Tom Sawyer*, Mark Twain, is known for saying, 'The man who does not read has no advantage over the man who cannot read.'",
  "Agatha Christie, the queen of mystery, wrote 66 detective novels featuring Hercule Poirot and Miss Marple.",
  "The first book ever written on a typewriter was *Tom Sawyer* by Mark Twain.",
  "Dr. Seuss invented the word 'nerd' in his book *If I Ran the Zoo*.",
  "The famous *Sherlock Holmes* stories by Arthur Conan Doyle were published as serials in magazines before becoming books.",
  "The *Gruffalo* by Julia Donaldson has been adapted into a stage play, a musical, and even a movie.",
  "The *Cat in the Hat* was published in 1957 and became one of the best-selling children's books in history.",
  "*The Wizard of Oz* was the first movie to use colored scenes throughout the film.",
  "The author of *The Jungle Book*, Rudyard Kipling, was born in India and is known for writing stories about animals.",
  "Hans Christian Andersen's story *The Ugly Duckling* was inspired by his own feelings of being different as a child.",
  "The world's largest book is a giant copy of the *Koran* at 5 meters by 8 meters in size, kept in Dubai.",
  "The very first book to be printed in English was *The Canterbury Tales* by Geoffrey Chaucer.",
  "The first known printed book in the world was the Diamond Sutra, a Buddhist text from China in 868 AD.",
  "The first person to sell a million copies of a book was Charles Dickens, with *A Tale of Two Cities*.",
  "The term 'novel' was first used to describe long fictional stories in the early 18th century.",
  "The first book ever printed in English was *The Canterbury Tales* by Geoffrey Chaucer.",
  "The most expensive book ever sold is Leonardo da Vinci's *Codex Leicester*, which was bought for $30.8 million.",
];

export default literaryFunFacts;
